---
title: X-Cart 5. Документация для разработчиков 
description: X-Cart 5. Документация для разработчиков
type: devs

# Paths
pages_path: _pages/devs_ru

# Urls
url: https://devs.x-cart.ru

# Search
search:
  preferred: devs.x-cart.ru

# Site settings
ga_code: UA-5826167-9
lang_default: ru