---
title: X-Cart 5 Knowledge Base
description: X-Cart 5 Knowledge Base
type: kb

# Paths
pages_path: _pages/kb_en

# Urls
url: https://kb.x-cart.com

# Search
search:
  preferred: kb.x-cart.com

# Site settings
lang_default: en