---
title: X-Cart 5 Knowledge Base
description: X-Cart 5 Knowledge Base

# Paths
pages: _pages/kb_en

# Urls
url: http://kb.x-cart.com

# Search
search:
  preferred: kb.x-cart.com

# Site settings
lang_default: en