# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
    environment:
          JEKYLL_DESTINATION: ~/repo/workspace
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run: mkdir -p workspace/build-targets

      - run: ./get_targets.sh workspace/build-targets

      - run: echo "$(ls -la workspace/build-targets)"

      - run: |
          if [ -f ~/repo/workspace/build-targets/devs_en ]; then
            echo "Building devs en"
            ./build.sh devs_en
          fi

      - run: |
          if [ -f ~/repo/workspace/build-targets/devs_ru ]; then
            echo "Building devs ru"
            ./build.sh devs_ru
          fi

      - run: |
          if [ -f ~/repo/workspace/build-targets/kb_en ]; then
            echo "Building kb en"
            ./build.sh kb_en
          fi

      - run: |
          if [ -f ~/repo/workspace/build-targets/kb_ru ]; then
            echo "Building kb ru"
            ./build.sh kb_ru
          fi