# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
    environment:
          JEKYLL_DESTINATION: _site
          CI_WORKSPACE: _workspace
          SSH_STRING: user@remote.host
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle check --path=vendor/bundle || bundle install --jobs=4 --retry=3 --path=vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run: rm -rf _workspace _site
      - run: mkdir -p _workspace/build-targets
      - run: mkdir -p _workspace/artifacts

      - run: ./get_targets.sh _workspace/build-targets

      - run: sudo apt-get install rsync

      - run: 
          name: Building devs en (if needed)
          command: |
            if [ -f ~/repo/_workspace/build-targets/devs_en ]; then
              ./build.sh devs_en
              rsync -zvh -e ssh _site/devs_en "$REMOTE_STRING:/site/devs_en" || true
              tar -czf _workspace/artifacts/devs_en.tar.gz _site/devs_en
            fi

      - run: 
          name: Building devs ru (if needed)
          command: |
            if [ -f ~/repo/_workspace/build-targets/devs_ru ]; then
              ./build.sh devs_ru
              rsync -zvh -e ssh _site/devs_ru "$REMOTE_STRING:/site/devs_ru" || true
              tar -czf _workspace/artifacts/devs_ru.tar.gz _site/devs_ru
            fi

      - run: 
          name: Building kb en (if needed)
          command: |
            if [ -f ~/repo/_workspace/build-targets/kb_en ]; then
              ./build.sh kb_en
              rsync -zvh -e ssh _site/kb_en "$REMOTE_STRING:/site/kb_en" || true
              tar -czf _workspace/artifacts/kb_en.tar.gz _site/kb_en
            fi

      - run: 
          name: Building kb ru (if needed)
          command: |
            if [ -f ~/repo/_workspace/build-targets/kb_ru ]; then
              ./build.sh kb_ru
              rsync -zvh -e ssh _site/kb_ru "$REMOTE_STRING:/site/kb_ru" || true
              tar -czf _workspace/artifacts/kb_ru.tar.gz _site/kb_ru
            fi

      - store_artifacts:
          path: _workspace/artifacts
