# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/ruby:2.4.1-node-browsers

version: 2
jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run: mkdir -p workspace/build-targets
      - run: ./get_targets.sh workspace/build-targets

      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: workspace
          # Must be relative path from root
          paths:
            - build-targets/devs_en
            - build-targets/devs_ru
            - build-targets/kb_en
            - build-targets/kb_ru

  build_devs_en:
    <<: *defaults
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/repo/workspace

      - run: |
          if [ -f ~/repo/workspace/build-targets/devs_en ]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi
  build_devs_ru:
    <<: *defaults
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/repo/workspace

      - run: |
          if [ -f ~/repo/workspace/build-targets/devs_ru ]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi
  build_kb_en:
    <<: *defaults
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/repo/workspace

      - run: |
          if [ -f ~/repo/workspace/build-targets/kb_en ]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi
  build_kb_ru:
    <<: *defaults
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/repo/workspace

      - run: |
          if [ -f ~/repo/workspace/build-targets/kb_ru ]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi

workflows:
  version: 2

  docs:
    jobs:
      - prepare
      - build_devs_en:
          requires:
            - prepare
      - build_devs_ru:
          requires:
            - prepare
      - build_kb_en:
          requires:
            - prepare
      - build_kb_ru:
          requires:
            - prepare
      - build_all:
          requires:
            - prepare
            