# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
    environment:
          JEKYLL_DESTINATION: _site
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run: mkdir -p workspace/build-targets
      - run: mkdir -p workspace/artifacts

      - run: ./get_targets.sh workspace/build-targets

      - run: 
          name: Building devs en (if needed)
          command: |
            if [ -f ~/repo/workspace/build-targets/devs_en ]; then
              ./build.sh devs_en
              tar -czf workspace/artifacts/devs_en.tar.gz _site/devs_en
            fi

      - run: 
          name: Building devs ru (if needed)
          command: |
            if [ -f ~/repo/workspace/build-targets/devs_ru ]; then
              ./build.sh devs_ru
              tar -czf workspace/artifacts/devs_ru.tar.gz _site/devs_ru
            fi

      - run: 
          name: Building kb en (if needed)
          command: |
            if [ -f ~/repo/workspace/build-targets/kb_en ]; then
              ./build.sh kb_en
              tar -czf workspace/artifacts/kb_en.tar.gz _site/kb_en
            fi

      - run: 
          name: Building kb ru (if needed)
          command: |
            if [ -f ~/repo/workspace/build-targets/kb_ru ]; then
              ./build.sh kb_ru
              tar -czf workspace/artifacts/kb_ru.tar.gz _site/kb_ru
            fi

      - store_artifacts:
          path: workspace/artifacts
